image: registry.gitlab.com/pathfinder-fr/foundryvtt-pathfinder2-fr

build:
    stage: build
    script:
        - git config --global user.email "pf2.fr.builder@gmail.com" && git config --global user.name "PF2FR Builder"
        - cd / && wget -q https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/jobs/artifacts/release/raw/pf2e.zip?job=build
        - unzip -q pf2e.zip?job=build && mv pf2e/packs /builds/pathfinder-fr/foundryvtt-pathfinder2-fr/packs
        - cd /builds/pathfinder-fr/ && git clone https://gitlab.com/pathfinder-fr/pf2-data-fr.git
        - cd /builds/pathfinder-fr/foundryvtt-pathfinder2-fr/scripts
        - bash update-ci.sh
        - cd /builds/pathfinder-fr/pf2-data-fr && git add -A && git commit -m "Automatic data update" && git push -o ci.skip https://root:$ACCESS_TOKEN@gitlab.com/pathfinder-fr/pf2-data-fr.git
    only:
        changes:
            - scripts/*
            - .gitlab-ci.yml
